# Generated by Django 5.0.2 on 2024-07-14 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='titile',
            new_name='title',
        ),
    ]
